remote_theme: jeffreytse/jekyll-theme-yat@v1.10.0

title: The Writing Blog
author: The Writing Blog
description: This description will show up in the meta tag, for SEO. You can also put a description in each post as well.