remote_theme: jeffreytse/jekyll-theme-yat

title: Your Blog Name
author: Your Name
description: This description will show up in the meta tag, for SEO. You can also put a description in each post as well.